####################
# Sample config
####################

# Directory containing the unzipped gspeechv2
data_root: ./data/

# CSV containing pairs of paths and labels, created by prepare_csv.py
train_csv: ./data/train_data.csv
val_csv: ./data/val_data.csv
test_csv: ./data/test_data.csv

# Experiment settings.
exp:
    wandb: False                         # If False, ignores wandb_api_key
    wandb_api_key: path/to/key.txt       # Path to api key. If blank, will prompt wandb login
    proj_name: torch-kwt                 # Wandb project name
    exp_dir: ./runs                      # Checkpoints, settings and logs of training runs will
    exp_name: exp-0                      #     be saved locally to {exp_dir}/{exp_name}.
                                         #     {exp_name} will also be used as the wandb run name.
    
    device: auto                         # Device: auto, cpu, cuda
    log_freq: 5                          # Log every log_freq steps
    val_freq: 1                          # Validate every val_freq epochs
    n_workers: 2                         # Number of worker processes for dataloader
    pin_memory: True                     # Pin memory for dataloader
    cache: False                         # Whether to load all data to memory or not
    
# Hyperparameters
hparams:
    seed: 0                              # For reproducibility. Can be left blank if desired.
    batch_size: 64                 
    n_epochs: 10
    init_lr: 0.001
    l_smooth: 0.1                        # Label smoothing.

    audio:
        sr: 16000
        n_mels: 40
        n_fft: 480
        win_length: 480
        hop_length: 160
        center: False
    
    model:   
        input_res: [98, 40]
        patch_res: [40, 1]
        num_classes: 35
        mlp_dim: 768
        dim: 192
        heads: 3
        depth: 12
        dropout: 0.0
        emb_dropout: 0.1

    optimizer:
        opt_type: AdamW
        weight_decay: 0.1
    
    scheduler:
        n_warmup: 10
        scheduler_type: cosine_annealing


    augment:
        resample:
            r_min: 0.85
            r_max: 1.15
        
        time_shift:
            s_min: -0.1
            s_max: 0.1

        bg_noise:
        #     bg_folder: ./data/_background_noise_/

        spec_aug:
            n_time_masks: 2
            time_mask_width: 25
            n_freq_masks: 2
            freq_mask_width: 7